export const FETCH_ALL_DATA = 'FETCH_ALL_DATA';
export const FETCH_ALL_DATA_SUCCESS = 'FETCH_ALL_DATA_SUCCESS';
export const FETCH_ALL_DATA_ERROR = 'FETCH_ALL_DATA_ERROR';

export const SET_LOADING = 'SET_LOADING';
export const SET_LOADED = 'SET_LOADED';
